---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-password
  namespace: default
spec:
  encryptedData:
    password: AgAl4ILJQJ/I2AjG13/+Cq+zlu0TZfDoa2jFlJPxXG+8rdM3qlVE6tltNi+6hsRV/D8UZZMeJnFftSPEDTto60Iy6uuA50rFLaQAH4aM/LkNbrvsVCqIgYZJ6PL4px01RPxDjed53rh5OpFDSgnT6q8LNmKVNfWE99KXf/IV9Cz2GvQKXhDvaYJ6Eww1mX0/3hb2VuQQQMNIdTlH1MlVF8y09hquSrDGXMRePJ6d/nXiUbK9QoR7znRGqyOJ61nHsG023eBaPPHIpdvAgh7raxhxoPElNCK8ggVKCOFsKqnpRKkdERWo3wvegGnbO7XYhDSllCNYcfwPZgMXRUhmpnC/rAX9WQRZ3jFdc8OynCaAxJb7+VzAFMsx2BkIhPiCpYVuskp9EfmtkJnc8mss8WN5++1VDTZbyBQB/ht+o/z++hqopAdDlZ+a3BwJ91sEc68YzGPUIfqF6206eHCQrv4ST/TUZu1iISyAbRKClXRYmftLeoP/4WHFE822WZTFgaP96XD9+fXqVtksTAWfu60P2+4lua/sQRjhA7afOBLkco40JYh0eAiYJoWisM8hIbjpn2gpXTVaez1SnQxHJFfwFqdd1EfFJO35lDOeKYSrAcK556uQ7tFbMoEzqtQgatPEURJqR1oi5HfJTBDjrqMoFujIXp8wUkBJNdXRlZaYGiBbYgNo4e6Gm/ZBPm0qhxtEwHWwrpkpZKga
  template:
    metadata:
      name: postgres-password
      namespace: default
