tag: "57da3dbde2595e0639f794f1d02b1ffcbda07128"

backend:
  image:
    repository: brachieldod/app-translator-backend
    tag: "57da3dbde2595e0639f794f1d02b1ffcbda07128"
  port: 3001

frontend:
  image:
    repository: brachieldod/app-translator-frontend
    tag: "57da3dbde2595e0639f794f1d02b1ffcbda07128"
  replicas: 1
  port: 80

translator:
  image: libretranslate/libretranslate:latest
  replicas: 1
  port: 5000

postgresql:
  auth:
    existingSecret: "postgres-password"
    secretKeys:
      adminPasswordKey: "password"
      userPasswordKey: "password"
    username: postgres
    database: translations
  primary:
    initdb:
      scripts:
        init.sql: |
          CREATE TABLE IF NOT EXISTS translations (
            id SERIAL PRIMARY KEY,
            source_text TEXT NOT NULL,
            target_lang VARCHAR(10) NOT NULL,
            translated_text TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT now()
          );
    persistence:
      enabled: true
      size: 10Gi
    nodeSelector:
      kubernetes.io/hostname: minikube

ingress:
  enabled: true
  host: translator.local