name: CI Frontend

on:
  push:
    branches: [main, feature/ci-cd]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  push:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/app-translator-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/app-translator-frontend:${{ github.sha }}