name: Full Deployment

on:
  push:
    branches: [ main ]

jobs:
  # שלב 1: פריסת ה-Frontend ל-S3
  deploy-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to S3
        run: aws s3 sync . s3://app-translator-frontend-bucket --delete --exclude ".git/*"


