name: Full Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync ./frontend s3://app-translator-frontend-bucket --delete --exclude ".git/*"

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: deploy-s3
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling new image..."
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app-translator-backend:latest

            echo "Stopping old container..."
            sudo docker stop my-app || true
            sudo docker rm my-app || true

            echo "Starting new container..."
            sudo docker run -d --name my-app -p 80:3001 ${{ secrets.DOCKERHUB_USERNAME }}/app-translator-backend:latest

            echo "Deployment finished!"